name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Hacer checkout del código
    - uses: actions/checkout@v4

    # Paso 2: Configurar JDK 23
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    # Paso 3: Construir con Maven 
    - name: Build with Maven
      run: mvn -B package -DskipTests --file UcoBet-Generales/pom.xml

    # Paso 4: Subir el artefacto generado (el archivo .jar)
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: ucoBet-artifact   # Nombre del artefacto que aparecerá en GitHub
        path: UcoBet-Generales/target/*.jar   # Ruta del archivo .jar generado
